spring:
  datasource:
    url: ${postgres.url}
    username: ${postgres.username}
    password: ${postgres.password}
  mvc:
    log-request-details: true
  jackson:
    property-naming-strategy: SNAKE_CASE

postgres:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: 1234

api:
  base-url: "https://api.themoviedb.org/3/"
  auth-token: ${token}

logging:
  level:
    org.springframework.web: DEBUG
    org.apache.hc.client5.http.wire: DEBUG
